### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by f4004** [TheMaverickProgrammer/Swoosh#6]
Hello. How can I get API documentation?

**Comment by TheMaverickProgrammer** [comment]
Hey! You can find a kind-of documentation on the wiki [here](https://github.com/TheMaverickProgrammer/Swoosh/wiki/Namespaces)

The repo comes with `ExampleDemo` which showcases making Activities (sometimes called Scenes) that run each screen and uses the `getController()` to push/pop activities.

See the example [here](https://github.com/TheMaverickProgrammer/Swoosh/tree/master/ExampleDemo/Swoosh/DemoActivities)

Towards the bottom of the README, there's a few sections on understanding the difference between Pushing, Popping, and Rewinding the activity controller. These commands effectively go to the Next Scene, Previous Scene, and Last Scene that matches a type. [Here](https://github.com/TheMaverickProgrammer/Swoosh/blob/master/README.md)

Here's a really [cool pokemon demo](https://github.com/janhkrueger/PokemonHeartGold-Swoosh) made with Swoosh. 

--- 

Let me know if that helps get you started!

**Comment by f4004** [comment]
Okay, thanks.

**Comment by TheMaverickProgrammer** [comment]
No problem. If you run into anything else, let me know and I'd be happy to help.
